let ingredients = [
    { idIng: '0', name: 'Pattes', local: '0', prix: '0.50' },
    { idIng: '1', name: 'Tomage', local: '1', prix: '1.50' },
    { idIng: '2', name: 'Boeuf', local: '1', prix: '4' },
    { idIng: '3', name: 'Lardons', local: '1', prix: '2.50' },
    { idIng: '4', name: 'Crême', local: '0', prix: '1' },
    { idIng: '5', name: 'Oeuf', local: '1', prix: '1' },
    { idIng: '6', name: 'Saumon', local: '0', prix: '5' },
    { idIng: '7', name: 'Aneth', local: '0', prix: '2' },
    { idIng: '8', name: 'Farine', local: '1', prix: '1.50' },
    { idIng: '9', name: 'Sucre', local: '0', prix: '1.50' },
    { idIng: '10', name: 'Chocolat', local: '0', prix: '2' },
    { idIng: '11', name: 'Noisettes', local: '1', prix: '3' },
    { idIng: '12', name: 'Salade', local: '1', prix: '1.50' },
    { idIng: '13', name: 'Maïs', local: '1', prix: '0.70' },
    { idIng: '14', name: 'Thon', local: '0', prix: '0.80' },
    { idIng: '15', name: 'Fromage', local: '1', prix: '1' },
    { idIng: '16', name: 'Boursin', local: '1', prix: '1' },
    { idIng: '17', name: 'Galette', local: '1', prix: '2' },
    { idIng: '18', name: 'Poulet', local: '1', prix: '4' },
    { idIng: '19', name: 'Pain', local: '1', prix: '0.80' },
    { idIng: '20', name: 'Beurre', local: '1', prix: '1' },
    { idIng: '21', name: 'Yahourt', local: '0', prix: '0.50' },
    { idIng: '22', name: 'Oignons', local: '1', prix: '0.50' },
];